name: Count Lines of Code per Language

on:
    workflow_dispatch:

jobs:
    count_lines:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cloc jq git

            - name: Clone Repositories
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  mkdir repos && cd repos
                  echo "Fetching repositories..."
                  curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/user/repos?per_page=100" > repos.json
                  for repo in $(jq -r '.[].clone_url' repos.json); do
                    echo "Cloning $repo"
                    git clone --depth 1 "$repo"
                  done

            - name: Print cloc JSON for Each Repository
              run: |
                  for repo in repos/*; do
                    echo "Processing repository: $repo"
                    cloc "$repo" --json
                  done
