name: Count Lines of Code per Language

on:
    workflow_dispatch:

jobs:
    count_lines:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cloc jq git

            - name: Clone Repositories
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  mkdir repos && cd repos
                  echo "Fetching repositories..."
                  curl -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/user/repos?per_page=100" > repos.json
                  for repo in $(jq -r '.[].clone_url' repos.json); do
                    echo "Cloning $repo"
                    git clone --depth 1 "$repo"
                  done

            - name: Count Lines of Code per Language
              run: |
                  echo "Running cloc on all repositories..."
                  # Run cloc on the repos directory and output in JSON format.
                  cloc_output=$(cloc repos --json)
                  echo "$cloc_output" > cloc.json
                  echo "Total lines of code per language:"
                  # Filter out the header and SUM fields and display only language entries.
                  jq 'to_entries | map(select(.key != "header" and .key != "SUM:")) | .[] | "\(.key): \(.value.code)"' cloc.json
